from bambu import mithep, analysis
import ROOT
import os

ROOT.gSystem.Load('libMitAnaPhysicsMod.so')
ROOT.gSystem.Load('libMitPhysicsMods.so')
ROOT.gSystem.Load('libMitPhysicsSelMods.so')
ROOT.gSystem.Load('libMitMonoJetMods.so')
ROOT.gSystem.Load('libMitMonoJetSelMods.so')
ROOT.gSystem.Load('libMitMonoJetTreeFiller.so')

mitData = os.environ['MIT_DATA']

isData = False

goodPVFilterMod = mithep.GoodPVFilterMod()
goodPVFilterMod.SetMinVertexNTracks(0)
goodPVFilterMod.SetMinNDof(4)
goodPVFilterMod.SetMaxAbsZ(24.0)
goodPVFilterMod.SetMaxRho(2.0)
goodPVFilterMod.SetIsMC(not isData)
goodPVFilterMod.SetVertexesName("PrimaryVertexes")

eleIdMod = mithep.ElectronIDMod()
eleIdMod.SetPtMin(10.)
eleIdMod.SetEtaMax(2.5)
eleIdMod.SetApplyEcalFiducial(True)
eleIdMod.SetIDType("VBTFWorkingPoint95Id")
eleIdMod.SetIsoType("PFIso")
eleIdMod.SetApplyConversionFilterType1(True)
eleIdMod.SetApplyConversionFilterType2(False)
eleIdMod.SetChargeFilter(False)
eleIdMod.SetApplyD0Cut(True)
eleIdMod.SetApplyDZCut(True)
eleIdMod.SetWhichVertex(0)
eleIdMod.SetNExpectedHitsInnerCut(0)
eleIdMod.SetGoodElectronsName("GoodElectronsBS")
eleIdMod.SetRhoType(mithep.RhoUtilities.CMS_RHO_RHOKT6PFJETS)

muonIdIsoMod = mithep.MuonIDMod()
muonIdIsoMod.SetOutputName("HWWMuons")
muonIdIsoMod.SetIntRadius(0.0)
muonIdIsoMod.SetClassType("GlobalTracker")
muonIdIsoMod.SetIDType("WWMuIdV4")
muonIdIsoMod.SetIsoType("IsoRingsV0_BDTG_Iso")
muonIdIsoMod.SetApplyD0Cut(True)
muonIdIsoMod.SetD0Cut(0.02)
muonIdIsoMod.SetApplyDZCut(True)
muonIdIsoMod.SetDZCut(0.1)
muonIdIsoMod.SetWhichVertex(0)
muonIdIsoMod.SetRhoType(mithep.RhoUtilities.CMS_RHO_RHOKT6PFJETS)
muonIdIsoMod.SetPtMin(10.)
muonIdIsoMod.SetEtaCut(2.4)

muonIdLooseMod = mithep.MuonIDMod()
muonIdLooseMod.SetOutputName("POGMuons")
muonIdLooseMod.SetClassType("GlobalTracker")
muonIdLooseMod.SetIDType("NoId")
muonIdLooseMod.SetIsoType("NoIso")
muonIdLooseMod.SetApplyD0Cut(True)
muonIdLooseMod.SetD0Cut(0.2)
muonIdLooseMod.SetApplyDZCut(True)
muonIdLooseMod.SetDZCut(0.5)
muonIdLooseMod.SetPtMin(10.)
muonIdLooseMod.SetEtaCut(2.4)
  
electronCleaning = mithep.ElectronCleaningMod()
electronCleaning.SetCleanMuonsName(muonIdLooseMod.GetOutputName())
electronCleaning.SetGoodElectronsName(eleIdMod.GetOutputName())
electronCleaning.SetCleanElectronsName("CleanElectrons")

merger = mithep.MergeLeptonsMod()
merger.SetMuonsName(muonIdLooseMod.GetOutputName())
merger.SetElectronsName(electronCleaning.GetOutputName())
merger.SetMergedName("MergedLeptons")

photonIdMod = mithep.PhotonIDMod()
photonIdMod.SetPtMin(10.0)
photonIdMod.SetOutputName("GoodPhotons")
photonIdMod.SetIDType("EgammaMedium")
photonIdMod.SetIsoType("NoIso")
photonIdMod.SetApplyElectronVeto(True)
photonIdMod.SetApplyPixelSeed(False)
photonIdMod.SetApplyConversionId(False)
photonIdMod.SetApplyFiduciality(True)
photonIdMod.SetIsData(isData)
photonIdMod.SetPhotonsFromBranch(True)

photonCleaningMod = mithep.PhotonCleaningMod()
photonCleaningMod.SetCleanElectronsName(electronCleaning.GetOutputName())
photonCleaningMod.SetGoodPhotonsName(photonIdMod.GetOutputName())
photonCleaningMod.SetCleanPhotonsName("CleanPhotons")

pftauIdMod = mithep.PFTauIDMod()
pftauIdMod.SetPFTausName("HPSTaus")
pftauIdMod.SetIsLooseId(True)
pftauIdMod.SetIsHPSSel(True)
pftauIdMod.SetPtMin(15)
  
pftauCleaningMod = mithep.PFTauCleaningMod()
pftauCleaningMod.SetGoodPFTausName(pftauIdMod.GetGoodPFTausName())
pftauCleaningMod.SetCleanMuonsName(muonIdLooseMod.GetOutputName())
pftauCleaningMod.SetCleanElectronsName(electronCleaning.GetOutputName())

pubAk4Jet = getattr(mithep, 'PublisherMod<mithep::PFJet,mithep::Jet>')('Akt4PFJetsPublisher')
pubAk4Jet.SetInputName("AKt4PFJets")
pubAk4Jet.SetOutputName("PubAKt4PFJets")

pubAk8Jet = getattr(mithep, 'PublisherMod<mithep::PFJet,mithep::Jet>')('Akt8PFJetsPublisher')
pubAk8Jet.SetInputName("AKt8PFJets")
pubAk8Jet.SetOutputName("PubAKt8PFJets")
        
ak4JetId = mithep.JetIDMod()
ak4JetId.SetInputName(pubAk4Jet.GetOutputName())
ak4JetId.SetPtCut(30.0)
ak4JetId.SetEtaMaxCut(2.5)
ak4JetId.SetJetEEMFractionMinCut(0.00)
ak4JetId.SetOutputName("GoodAk4Jets")
ak4JetId.SetApplyPFLooseId(True)

ak8JetId = mithep.JetIDMod()
ak8JetId.SetInputName(pubAk8Jet.GetOutputName())
ak8JetId.SetPtCut(30.0)
ak8JetId.SetEtaMaxCut(2.5)
ak8JetId.SetJetEEMFractionMinCut(0.00)
ak8JetId.SetOutputName("GoodAk8Jets")

#jetCleaning = mithep.JetCleaningMod()
#jetCleaning.SetCleanElectronsName(electronCleaning.GetOutputName())
#jetCleaning.SetCleanMuonsName(muonIdIsoMod.GetOutputName())
#jetCleaning.SetCleanPhotonsName(photonCleaningMod.GetOutputName())
#jetCleaning.SetApplyPhotonRemoval(True)
#jetCleaning.SetApplyTauRemoval(False)
#jetCleaning.SetGoodJetsName(ak4JetId.GetOutputName())
#jetCleaning.SetCleanJetsName("CleanJets")
#
#fatJetCleaning = mithep.JetCleaningMod()
#fatJetCleaning.SetCleanElectronsName(electronCleaning.GetOutputName())
#fatJetCleaning.SetCleanMuonsName(muonIdIsoMod.GetOutputName())
#fatJetCleaning.SetCleanPhotonsName(photonCleaningMod.GetOutputName())
#fatJetCleaning.SetMinDeltaRToElectron(0.5)
#fatJetCleaning.SetMinDeltaRToMuon(0.5)
#fatJetCleaning.SetMinDeltaRToPhoton(0.5)
#fatJetCleaning.SetApplyPhotonRemoval(True)
#fatJetCleaning.SetApplyTauRemoval(False)  
#fatJetCleaning.SetGoodJetsName(ak8JetId.GetOutputName())
#fatJetCleaning.SetCleanJetsName("CleanFatJets")

jetplusmet = mithep.BoostedVAnalysisMod("MonoJetSelector")
jetplusmet.SetFatJetsName(fatJetCleaning.GetOutputName())
jetplusmet.SetFatJetsFromBranch(False)
jetplusmet.SetJetsName(jetCleaning.GetOutputName())
jetplusmet.SetJetsFromBranch(False)
jetplusmet.SetElectronsName(electronCleaning.GetOutputName())
jetplusmet.SetElectronsFromBranch(False)
jetplusmet.SetMuonsName(muonIdLooseMod.GetOutputName())
jetplusmet.SetMuonsFromBranch(False)
jetplusmet.SetPhotonsName(photonCleaningMod.GetOutputName())
jetplusmet.SetPhotonsFromBranch(False)
jetplusmet.ApplyResolvedPresel(True) 
jetplusmet.ApplyTopPresel(False) 
jetplusmet.ApplyWlepPresel(True)
jetplusmet.ApplyZmmPresel(True)
jetplusmet.ApplyMetPresel(True)
jetplusmet.ApplyVbfPresel(False)
jetplusmet.ApplyGjetPresel(True)
jetplusmet.SetMinFatJetPt(200)
jetplusmet.SetMinTagJetPt(110)
jetplusmet.SetMinMet(150)    
jetplusmet.SetMinPhotonPt(160)    
jetplusmet.SkipEvents(False)    

extendedMetFiller = mithep.FillerXlMet()
extendedMetFiller.SetIsData(isData)
extendedMetFiller.SetJetsFromBranch(False)
extendedMetFiller.SetJetsName(pubAk4Jet.GetOutputName())
extendedMetFiller.SetMuonsFromBranch(True)
extendedMetFiller.SetElectronsFromBranch(True)
extendedMetFiller.SetTausFromBranch(True)
extendedMetFiller.SetTausName("HPSTaus")
extendedMetFiller.SetPhotonsFromBranch(True)
extendedMetFiller.SetPVFromBranch(False)
extendedMetFiller.SetPVName(goodPVFilterMod.GetOutputName())
extendedMetFiller.SetXlMetName("PFMetMVA")     

boostedJetsFiller = mithep.FillerXlJets() 
boostedJetsFiller.SetJetsName(jetCleaning.GetOutputName())
boostedJetsFiller.SetJetsFromBranch(False)

boostedFatJetsFiller = mithep.FillerXlFatJets()
boostedFatJetsFiller.FillTopSubJets(False)
boostedFatJetsFiller.SetJetsName(fatJetCleaning.GetOutputName())
boostedFatJetsFiller.SetJetsFromBranch(False)
boostedFatJetsFiller.SetConeSize(0.8)      

boostedXsIsoParticlesFiller = mithep.FillerXsIsoParticles()
boostedXsIsoParticlesFiller.FillXsMuons(True)
boostedXsIsoParticlesFiller.FillXsElectrons(True)
boostedXsIsoParticlesFiller.FillXsTaus(True)
boostedXsIsoParticlesFiller.FillXsPhotons(True)
boostedXsIsoParticlesFiller.SetMuonsName(muonIdLooseMod.GetOutputName())
boostedXsIsoParticlesFiller.SetMuonsFromBranch(False)
boostedXsIsoParticlesFiller.SetIsoMuonsName(muonIdIsoMod.GetOutputName())
boostedXsIsoParticlesFiller.SetIsoMuonsFromBranch(False)
boostedXsIsoParticlesFiller.SetElectronsName(eleIdMod.GetOutputName())
boostedXsIsoParticlesFiller.SetElectronsFromBranch(False)
boostedXsIsoParticlesFiller.SetTausName(pftauCleaningMod.GetOutputName())
boostedXsIsoParticlesFiller.SetTausFromBranch(False)
boostedXsIsoParticlesFiller.SetPhotonsName(photonCleaningMod.GetOutputName())
boostedXsIsoParticlesFiller.SetPhotonsFromBranch(False)

skmPFCandidates = getattr(mithep, 'SkimMod<mithep::PFCandidate>')()

skmJets = mithep.SkimJetsMod()
skmJets.SetBranchName(jetCleaning.GetOutputName())
skmJets.SetColFromBranch(False)
skmJets.SetColMarkFilter(False)
skmJets.SetPublishArray(True)
   
outMod = mithep.OutputMod()
outMod.SetUseBrDep(False)
outMod.SetKeepTamBr(False)
outMod.SetFileName('ntuples.root')
outMod.SetMaxFileSize(4096)
outMod.Drop("*")
outMod.Keep(mithep.Names.gkMCEvtInfoBrn)
outMod.Keep(mithep.Names.gkMCPartBrn)
outMod.Keep(mithep.Names.gkPVBeamSpotBrn)
outMod.Keep(mithep.Names.gkPileupInfoBrn)
outMod.Keep(mithep.Names.gkPileupEnergyDensityBrn)
outMod.Keep("PFMet")
outMod.AddNewBranch("XlEvtSelData")
outMod.AddNewBranch("PFMetMVA")
outMod.AddNewBranch("XlJets")
outMod.AddNewBranch("XlFatJets")
outMod.AddNewBranch("XlSubJets")
outMod.AddNewBranch("XsMuons")
outMod.AddNewBranch("XsElectrons")
outMod.AddNewBranch("XsTaus")
outMod.AddNewBranch("XsPhotons")
  
goodPVFilterMod.Add(muonIdIsoMod)
muonIdIsoMod.Add(muonIdLooseMod)
muonIdLooseMod.Add(eleIdMod)
eleIdMod.Add(electronCleaning)
electronCleaning.Add(merger)
merger.Add(photonIdMod)
photonIdMod.Add(photonCleaningMod)
photonCleaningMod.Add(pftauIdMod)
pftauIdMod.Add(pftauCleaningMod)
pftauCleaningMod.Add(pubAk4Jet)
pubAk4Jet.Add(jetCorr)
jetCorr.Add(ak4JetId)
ak4JetId.Add(jetCleaning)
jetCleaning.Add(pubFastJet)
pubFastJet.Add(fatJetCorr)
fatJetCorr.Add(ak8JetId)
ak8JetId.Add(fatJetCleaning)
fatJetCleaning.Add(jetplusmet)
jetplusmet.Add(extendedMetFiller)
extendedMetFiller.Add(boostedJetsFiller)
boostedJetsFiller.Add(boostedFatJetsFiller)
boostedFatJetsFiller.Add(boostedXsIsoParticlesFiller)
boostedXsIsoParticlesFiller.Add(skmJets)
skmJets.Add(outMod)

analysis.SetUseHLT(False)
analysis.SetSuperModule(goodPVFilterMod)
analysis.SetPrintScale(100)
